### ISSUE TITLE
integrate with groq

### ISSUE THREAD

**Issue by Powerostad** [emirsahin1/llm-axe#14]
Hello, I just want to know can i integrate it with groq API?
it's the ollama models within api.

**Comment by emirsahin1** [comment]
Hi, yes this is totally possible. You have to define a custom llm class that llm-axe can use to talk to Groq.
I'll eventually add this into llm-axe as a built in class but here is the code you need to do that:

```python

from groq import Groq
from llm_axe import Agent, AgentType

class GroqChat():
    def __init__(self, api_key:str, model:str=None):
        self._model = model
        self._client = Groq(api_key=api_key)

    def ask(self, prompts:list, format:str="", temperature:float=0.8):
        resp_format = "json_object" if format == "json" else "text"
        return self._client.chat.completions.create(messages=prompts, 
                                                    model=self._model, 
                                                    response_format={"type": resp_format},  
                                                    temperature=temperature).choices[0].message.content
    

llm = GroqChat(model="llama3-8b-8192", api_key="KEY GOES HERE")
ag = Agent(agent_type=AgentType.GENERIC_RESPONDER, llm=llm)
resp = ag.ask("How are you doing?")
print(resp)

```

Let me know if you run into any issues. Thanks!

**Comment by Powerostad** [comment]
> Hi, yes this is totally possible. You have to define a custom llm class that llm-axe can use to talk to Groq. I'll eventually add this into llm-axe as a built in class but here is the code you need to do that:
> 
> ```python
> from groq import Groq
> from llm_axe import Agent, AgentType
> 
> class GroqChat():
>     def __init__(self, api_key:str, model:str=None):
>         self._model = model
>         self._client = Groq(api_key=api_key)
> 
>     def ask(self, prompts:list, format:str="", temperature:float=0.8):
>         resp_format = "json_object" if format == "json" else "text"
>         return self._client.chat.completions.create(messages=prompts, 
>                                                     model=self._model, 
>                                                     response_format={"type": resp_format},  
>                                                     temperature=temperature).choices[0].message.content
>     
> 
> llm = GroqChat(model="llama3-8b-8192", api_key="KEY GOES HERE")
> ag = Agent(agent_type=AgentType.GENERIC_RESPONDER, llm=llm)
> resp = ag.ask("How are you doing?")
> print(resp)
> ```
> 
> Let me know if you run into any issues. Thanks!

Thank you that work perfectly. i will modify and add some customization and contribute
