### ISSUE TITLE
Build Issue.

### ISSUE THREAD

**Issue by yoni13** [emirsahin1/llm-axe#7]
Hello, I am trying to use this amazing module to build my llm app, When I was trying to make changes to the repo and build to test it, there was no standard setup.py or pyproject.toml provided.
Can you provide your setup.py or pyproject.toml to make the module installable from the source?

**Comment by emirsahin1** [comment]
Apologies for the oversight. I've added setup.py and __init__.py to the repository.

The command I use to build:
```bash
python setup.py sdist bdist_wheel
```

**Comment by yoni13** [comment]
It worked, thanks.

**Comment by emirsahin1** [comment]
Try placing the setup file outside of the main directory in a parent folder. That's how I've been building for release. 

Let me know if that works.

**Comment by yoni13** [comment]
> Try placing the setup file outside of the main directory in a parent folder. That's how I've been building for release.
> 
> Let me know if that works.

I re-structured the module to make it work, if you think the old one is better, let me know and I will change it back, thanks!
